///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RanorexFramework.Pages.Introduction
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The MOD_EnterName recording.
    /// </summary>
    [TestModule("01cb9d01-974c-4f21-b9bb-75ee8eeb89e5", ModuleType.Recording, 1)]
    public partial class MOD_EnterName : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::RanorexFramework.Repository.RanorexFrameworkRepository repository.
        /// </summary>
        public static global::RanorexFramework.Repository.RanorexFrameworkRepository repo = global::RanorexFramework.Repository.RanorexFrameworkRepository.Instance;

        static MOD_EnterName instance = new MOD_EnterName();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public MOD_EnterName()
        {
            SampleName = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static MOD_EnterName Instance
        {
            get { return instance; }
        }

#region Variables

        string _SampleName;

        /// <summary>
        /// Gets or sets the value of variable SampleName.
        /// </summary>
        [TestVariable("799cfd7e-539e-4f3f-8826-d4e8a53ed8a7")]
        public string SampleName
        {
            get { return _SampleName; }
            set { _SampleName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.Introduction.TxtUserName' at 47;14.", repo.RxMainFrame.Introduction.TxtUserNameInfo, new RecordItemIndex(0));
            repo.RxMainFrame.Introduction.TxtUserName.Click("47;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'RxMainFrame.Introduction.TxtUserName'.", repo.RxMainFrame.Introduction.TxtUserNameInfo, new RecordItemIndex(1));
            Validate.Exists(repo.RxMainFrame.Introduction.TxtUserNameInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'RxMainFrame.Introduction.BtnSubmitUserName'.", repo.RxMainFrame.Introduction.BtnSubmitUserNameInfo, new RecordItemIndex(2));
            Validate.Exists(repo.RxMainFrame.Introduction.BtnSubmitUserNameInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'RxMainFrame.Introduction.TxtUserName'.", repo.RxMainFrame.Introduction.TxtUserNameInfo, new RecordItemIndex(3));
            Validate.Exists(repo.RxMainFrame.Introduction.TxtUserNameInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$SampleName' with focus on 'RxMainFrame.Introduction.TxtUserName'.", repo.RxMainFrame.Introduction.TxtUserNameInfo, new RecordItemIndex(4));
            repo.RxMainFrame.Introduction.TxtUserName.PressKeys(SampleName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'RxMainFrame.Introduction.BtnSubmitUserName' at Center", repo.RxMainFrame.Introduction.BtnSubmitUserNameInfo, new RecordItemIndex(5));
            repo.RxMainFrame.Introduction.BtnSubmitUserName.Touch();
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeRegex (Text~'Welcome, .*!') on item 'RxMainFrame.Introduction.LblWelcomeMessage'.", repo.RxMainFrame.Introduction.LblWelcomeMessageInfo, new RecordItemIndex(6));
            Validate.AttributeRegex(repo.RxMainFrame.Introduction.LblWelcomeMessageInfo, "Text", new Regex("Welcome, .*!"));
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.Introduction.RxLinkBtnReset' at 27;13.", repo.RxMainFrame.Introduction.RxLinkBtnResetInfo, new RecordItemIndex(7));
            repo.RxMainFrame.Introduction.RxLinkBtnReset.Click("27;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Welcome!') on item 'RxMainFrame.Introduction.LblWelcomeMessage'.", repo.RxMainFrame.Introduction.LblWelcomeMessageInfo, new RecordItemIndex(8));
            Validate.AttributeEqual(repo.RxMainFrame.Introduction.LblWelcomeMessageInfo, "Text", "Welcome!");
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.RxMainFrame.Self, false, new RecordItemIndex(9));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
