///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RanorexFramework.Pages.Introduction
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The MOD_ValidateBanner recording.
    /// </summary>
    [TestModule("5c678e57-6c22-40fc-abc1-0e9328bd1148", ModuleType.Recording, 1)]
    public partial class MOD_ValidateBanner : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::RanorexFramework.Repository.RanorexFrameworkRepository repository.
        /// </summary>
        public static global::RanorexFramework.Repository.RanorexFrameworkRepository repo = global::RanorexFramework.Repository.RanorexFrameworkRepository.Instance;

        static MOD_ValidateBanner instance = new MOD_ValidateBanner();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public MOD_ValidateBanner()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static MOD_ValidateBanner Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'RxMainFrame.Introduction.LblWelcomeMessage'.", repo.RxMainFrame.Introduction.LblWelcomeMessageInfo, new RecordItemIndex(0));
            Validate.Exists(repo.RxMainFrame.Introduction.LblWelcomeMessageInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Welcome!') on item 'RxMainFrame.Introduction.LblWelcomeMessage'.", repo.RxMainFrame.Introduction.LblWelcomeMessageInfo, new RecordItemIndex(1));
            Validate.AttributeEqual(repo.RxMainFrame.Introduction.LblWelcomeMessageInfo, "Text", "Welcome!");
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.RxMainFrame.Self, false, new RecordItemIndex(2));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
