///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RanorexFramework.Pages.Test_Database
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The MOD_DeleteEntry recording.
    /// </summary>
    [TestModule("cb87304c-8524-496f-8b9f-768a1cce6e91", ModuleType.Recording, 1)]
    public partial class MOD_DeleteEntry : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::RanorexFramework.Repository.RanorexFrameworkRepository repository.
        /// </summary>
        public static global::RanorexFramework.Repository.RanorexFrameworkRepository repo = global::RanorexFramework.Repository.RanorexFrameworkRepository.Instance;

        static MOD_DeleteEntry instance = new MOD_DeleteEntry();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public MOD_DeleteEntry()
        {
            Database_FirstName = "";
            Database_LastName = "";
            Database_Department = "";
            Database_Age = "";
            Database_Gender = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static MOD_DeleteEntry Instance
        {
            get { return instance; }
        }

#region Variables

        string _Database_FirstName;

        /// <summary>
        /// Gets or sets the value of variable Database_FirstName.
        /// </summary>
        [TestVariable("62b5e8e4-3d60-4992-aba6-4f3574b3f1d5")]
        public string Database_FirstName
        {
            get { return _Database_FirstName; }
            set { _Database_FirstName = value; }
        }

        string _Database_LastName;

        /// <summary>
        /// Gets or sets the value of variable Database_LastName.
        /// </summary>
        [TestVariable("66d0bf7f-d1aa-47ba-8a0e-d458c4ff86f0")]
        public string Database_LastName
        {
            get { return _Database_LastName; }
            set { _Database_LastName = value; }
        }

        string _Database_Department;

        /// <summary>
        /// Gets or sets the value of variable Database_Department.
        /// </summary>
        [TestVariable("a5207f78-ed4a-4472-b070-1940582aa887")]
        public string Database_Department
        {
            get { return _Database_Department; }
            set { _Database_Department = value; }
        }

        string _Database_Age;

        /// <summary>
        /// Gets or sets the value of variable Database_Age.
        /// </summary>
        [TestVariable("a35db305-df97-4d3f-8fd8-65cb3fa8b17f")]
        public string Database_Age
        {
            get { return _Database_Age; }
            set { _Database_Age = value; }
        }

        string _Database_Gender;

        /// <summary>
        /// Gets or sets the value of variable Database_Gender.
        /// </summary>
        [TestVariable("c5437c3e-aaf1-4725-827a-ea1315ca825f")]
        public string Database_Gender
        {
            get { return _Database_Gender; }
            set { _Database_Gender = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'RxMainFrame.Tabs.RxTabcontrol'.", repo.RxMainFrame.Tabs.RxTabcontrolInfo, new RecordItemIndex(0));
            Validate.Exists(repo.RxMainFrame.Tabs.RxTabcontrolInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute SelectedIndex to '1' on item 'RxMainFrame.Tabs.RxTabcontrol'.", repo.RxMainFrame.Tabs.RxTabcontrolInfo, new RecordItemIndex(1));
            repo.RxMainFrame.Tabs.RxTabcontrol.Element.SetAttributeValue("SelectedIndex", "1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'RxMainFrame.Test_Database.TxtFirstName'.", repo.RxMainFrame.Test_Database.TxtFirstNameInfo, new RecordItemIndex(2));
            Validate.Exists(repo.RxMainFrame.Test_Database.TxtFirstNameInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'RxMainFrame.Test_Database.TxtLastName'.", repo.RxMainFrame.Test_Database.TxtLastNameInfo, new RecordItemIndex(3));
            Validate.Exists(repo.RxMainFrame.Test_Database.TxtLastNameInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'RxMainFrame.Test_Database.Department'.", repo.RxMainFrame.Test_Database.DepartmentInfo, new RecordItemIndex(4));
            Validate.Exists(repo.RxMainFrame.Test_Database.DepartmentInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'RxMainFrame.Test_Database.Age'.", repo.RxMainFrame.Test_Database.AgeInfo, new RecordItemIndex(5));
            Validate.Exists(repo.RxMainFrame.Test_Database.AgeInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'RxMainFrame.Test_Database.GenderFemale'.", repo.RxMainFrame.Test_Database.GenderFemaleInfo, new RecordItemIndex(6));
            Validate.Exists(repo.RxMainFrame.Test_Database.GenderFemaleInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'RxMainFrame.Test_Database.GenderMale'.", repo.RxMainFrame.Test_Database.GenderMaleInfo, new RecordItemIndex(7));
            Validate.Exists(repo.RxMainFrame.Test_Database.GenderMaleInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'RxMainFrame.Test_Database.BtnAddPerson'.", repo.RxMainFrame.Test_Database.BtnAddPersonInfo, new RecordItemIndex(8));
            Validate.Exists(repo.RxMainFrame.Test_Database.BtnAddPersonInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.Test_Database.TxtFirstName' at 114;13.", repo.RxMainFrame.Test_Database.TxtFirstNameInfo, new RecordItemIndex(9));
            repo.RxMainFrame.Test_Database.TxtFirstName.Click("114;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Database_FirstName' with focus on 'RxMainFrame.Test_Database.TxtFirstName'.", repo.RxMainFrame.Test_Database.TxtFirstNameInfo, new RecordItemIndex(10));
            repo.RxMainFrame.Test_Database.TxtFirstName.PressKeys(Database_FirstName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.Test_Database.TxtLastName' at 62;19.", repo.RxMainFrame.Test_Database.TxtLastNameInfo, new RecordItemIndex(11));
            repo.RxMainFrame.Test_Database.TxtLastName.Click("62;19");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Database_LastName' with focus on 'RxMainFrame.Test_Database.TxtLastName'.", repo.RxMainFrame.Test_Database.TxtLastNameInfo, new RecordItemIndex(12));
            repo.RxMainFrame.Test_Database.TxtLastName.PressKeys(Database_LastName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '$Database_Department' on item 'RxMainFrame.Test_Database.Department'.", repo.RxMainFrame.Test_Database.DepartmentInfo, new RecordItemIndex(13));
            repo.RxMainFrame.Test_Database.Department.Element.SetAttributeValue("Text", Database_Department);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '$Database_Age' on item 'RxMainFrame.Test_Database.Age'.", repo.RxMainFrame.Test_Database.AgeInfo, new RecordItemIndex(14));
            repo.RxMainFrame.Test_Database.Age.Element.SetAttributeValue("Text", Database_Age);
            Delay.Milliseconds(0);
            
            Mouse_Click_Gender(Database_Gender);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.Test_Database.BtnAddPerson' at Center.", repo.RxMainFrame.Test_Database.BtnAddPersonInfo, new RecordItemIndex(16));
            repo.RxMainFrame.Test_Database.BtnAddPerson.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='1') on item 'RxMainFrame.Test_Database.LblNumberOfPersonsNumber'.", repo.RxMainFrame.Test_Database.LblNumberOfPersonsNumberInfo, new RecordItemIndex(17));
            Validate.AttributeEqual(repo.RxMainFrame.Test_Database.LblNumberOfPersonsNumberInfo, "Text", "1");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.Test_Database.DatabaseList' at 228;12.", repo.RxMainFrame.Test_Database.DatabaseListInfo, new RecordItemIndex(18));
            repo.RxMainFrame.Test_Database.DatabaseList.Click("228;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.Test_Database.BtnDeletePerson' at Center.", repo.RxMainFrame.Test_Database.BtnDeletePersonInfo, new RecordItemIndex(19));
            repo.RxMainFrame.Test_Database.BtnDeletePerson.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='0') on item 'RxMainFrame.Test_Database.LblNumberOfPersonsNumber'.", repo.RxMainFrame.Test_Database.LblNumberOfPersonsNumberInfo, new RecordItemIndex(20));
            Validate.AttributeEqual(repo.RxMainFrame.Test_Database.LblNumberOfPersonsNumberInfo, "Text", "0");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
