///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RanorexFramework.Pages.Test_Database
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The MOD_AddDatabaseEntry recording.
    /// </summary>
    [TestModule("ebe14057-42c6-4e66-9067-d3db8a31bc97", ModuleType.Recording, 1)]
    public partial class MOD_AddDatabaseEntry : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::RanorexFramework.Repository.RanorexFrameworkRepository repository.
        /// </summary>
        public static global::RanorexFramework.Repository.RanorexFrameworkRepository repo = global::RanorexFramework.Repository.RanorexFrameworkRepository.Instance;

        static MOD_AddDatabaseEntry instance = new MOD_AddDatabaseEntry();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public MOD_AddDatabaseEntry()
        {
            Database_FirstName = "";
            Database_LastName = "";
            Database_Department = "";
            Database_Age = "";
            Database_Gender = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static MOD_AddDatabaseEntry Instance
        {
            get { return instance; }
        }

#region Variables

        string _Database_FirstName;

        /// <summary>
        /// Gets or sets the value of variable Database_FirstName.
        /// </summary>
        [TestVariable("9406d0dc-31b2-46f1-bc86-e1d5dbf0d9b7")]
        public string Database_FirstName
        {
            get { return _Database_FirstName; }
            set { _Database_FirstName = value; }
        }

        string _Database_LastName;

        /// <summary>
        /// Gets or sets the value of variable Database_LastName.
        /// </summary>
        [TestVariable("3b8e7484-8b71-465c-953c-9dcbec56ac8a")]
        public string Database_LastName
        {
            get { return _Database_LastName; }
            set { _Database_LastName = value; }
        }

        string _Database_Department;

        /// <summary>
        /// Gets or sets the value of variable Database_Department.
        /// </summary>
        [TestVariable("e7f67630-9dba-4873-af56-ea425e409b84")]
        public string Database_Department
        {
            get { return _Database_Department; }
            set { _Database_Department = value; }
        }

        string _Database_Age;

        /// <summary>
        /// Gets or sets the value of variable Database_Age.
        /// </summary>
        [TestVariable("2b197126-a414-4ceb-ae34-52cfd92d01af")]
        public string Database_Age
        {
            get { return _Database_Age; }
            set { _Database_Age = value; }
        }

        string _Database_Gender;

        /// <summary>
        /// Gets or sets the value of variable Database_Gender.
        /// </summary>
        [TestVariable("c32fef97-df12-4685-be57-02cc3ac948dd")]
        public string Database_Gender
        {
            get { return _Database_Gender; }
            set { _Database_Gender = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'RxMainFrame.Tabs.RxTabcontrol'.", repo.RxMainFrame.Tabs.RxTabcontrolInfo, new RecordItemIndex(0));
            Validate.Exists(repo.RxMainFrame.Tabs.RxTabcontrolInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute SelectedIndex to '1' on item 'RxMainFrame.Tabs.RxTabcontrol'.", repo.RxMainFrame.Tabs.RxTabcontrolInfo, new RecordItemIndex(1));
            repo.RxMainFrame.Tabs.RxTabcontrol.Element.SetAttributeValue("SelectedIndex", "1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'RxMainFrame.Test_Database.TxtFirstName'.", repo.RxMainFrame.Test_Database.TxtFirstNameInfo, new RecordItemIndex(2));
            Validate.Exists(repo.RxMainFrame.Test_Database.TxtFirstNameInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'RxMainFrame.Test_Database.TxtLastName'.", repo.RxMainFrame.Test_Database.TxtLastNameInfo, new RecordItemIndex(3));
            Validate.Exists(repo.RxMainFrame.Test_Database.TxtLastNameInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'RxMainFrame.Test_Database.Department'.", repo.RxMainFrame.Test_Database.DepartmentInfo, new RecordItemIndex(4));
            Validate.Exists(repo.RxMainFrame.Test_Database.DepartmentInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'RxMainFrame.Test_Database.Age'.", repo.RxMainFrame.Test_Database.AgeInfo, new RecordItemIndex(5));
            Validate.Exists(repo.RxMainFrame.Test_Database.AgeInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'RxMainFrame.Test_Database.GenderFemale'.", repo.RxMainFrame.Test_Database.GenderFemaleInfo, new RecordItemIndex(6));
            Validate.Exists(repo.RxMainFrame.Test_Database.GenderFemaleInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'RxMainFrame.Test_Database.GenderMale'.", repo.RxMainFrame.Test_Database.GenderMaleInfo, new RecordItemIndex(7));
            Validate.Exists(repo.RxMainFrame.Test_Database.GenderMaleInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'RxMainFrame.Test_Database.BtnAddPerson'.", repo.RxMainFrame.Test_Database.BtnAddPersonInfo, new RecordItemIndex(8));
            Validate.Exists(repo.RxMainFrame.Test_Database.BtnAddPersonInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.Test_Database.TxtFirstName' at 114;13.", repo.RxMainFrame.Test_Database.TxtFirstNameInfo, new RecordItemIndex(9));
            repo.RxMainFrame.Test_Database.TxtFirstName.Click("114;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Database_FirstName' with focus on 'RxMainFrame.Test_Database.TxtFirstName'.", repo.RxMainFrame.Test_Database.TxtFirstNameInfo, new RecordItemIndex(10));
            repo.RxMainFrame.Test_Database.TxtFirstName.PressKeys(Database_FirstName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.Test_Database.TxtLastName' at 62;19.", repo.RxMainFrame.Test_Database.TxtLastNameInfo, new RecordItemIndex(11));
            repo.RxMainFrame.Test_Database.TxtLastName.Click("62;19");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Database_LastName' with focus on 'RxMainFrame.Test_Database.TxtLastName'.", repo.RxMainFrame.Test_Database.TxtLastNameInfo, new RecordItemIndex(12));
            repo.RxMainFrame.Test_Database.TxtLastName.PressKeys(Database_LastName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '$Database_Department' on item 'RxMainFrame.Test_Database.Department'.", repo.RxMainFrame.Test_Database.DepartmentInfo, new RecordItemIndex(13));
            repo.RxMainFrame.Test_Database.Department.Element.SetAttributeValue("Text", Database_Department);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '$Database_Age' on item 'RxMainFrame.Test_Database.Age'.", repo.RxMainFrame.Test_Database.AgeInfo, new RecordItemIndex(14));
            repo.RxMainFrame.Test_Database.Age.Element.SetAttributeValue("Text", Database_Age);
            Delay.Milliseconds(0);
            
            Mouse_Click_Gender(Database_Gender);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.Test_Database.BtnAddPerson' at Center.", repo.RxMainFrame.Test_Database.BtnAddPersonInfo, new RecordItemIndex(16));
            repo.RxMainFrame.Test_Database.BtnAddPerson.Click();
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.RxMainFrame.Self, false, new RecordItemIndex(17));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
