///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace RanorexFramework.Repository
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the RanorexFrameworkRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("21d1b953-4c62-4f21-a4ce-cff2ddc0999b")]
    public partial class RanorexFrameworkRepository : RepoGenBaseFolder
    {
        static RanorexFrameworkRepository instance = new RanorexFrameworkRepository();
        RanorexFrameworkRepositoryFolders.RxMainFrameAppFolder _rxmainframe;

        /// <summary>
        /// Gets the singleton class instance representing the RanorexFrameworkRepository element repository.
        /// </summary>
        [RepositoryFolder("21d1b953-4c62-4f21-a4ce-cff2ddc0999b")]
        public static RanorexFrameworkRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public RanorexFrameworkRepository() 
            : base("RanorexFrameworkRepository", "/", null, 0, false, "21d1b953-4c62-4f21-a4ce-cff2ddc0999b", ".\\RepositoryImages\\RanorexFrameworkRepository21d1b953.rximgres")
        {
            _rxmainframe = new RanorexFrameworkRepositoryFolders.RxMainFrameAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("21d1b953-4c62-4f21-a4ce-cff2ddc0999b")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The RxMainFrame folder.
        /// </summary>
        [RepositoryFolder("547664e6-4cf3-4efa-ab0b-92a0f641feb9")]
        public virtual RanorexFrameworkRepositoryFolders.RxMainFrameAppFolder RxMainFrame
        {
            get { return _rxmainframe; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class RanorexFrameworkRepositoryFolders
    {
        /// <summary>
        /// The RxMainFrameAppFolder folder.
        /// </summary>
        [RepositoryFolder("547664e6-4cf3-4efa-ab0b-92a0f641feb9")]
        public partial class RxMainFrameAppFolder : RepoGenBaseFolder
        {
            RanorexFrameworkRepositoryFolders.TabsFolder _tabs;
            RanorexFrameworkRepositoryFolders.IntroductionFolder _introduction;
            RanorexFrameworkRepositoryFolders.Test_DatabaseFolder _test_database;

            /// <summary>
            /// Creates a new RxMainFrame  folder.
            /// </summary>
            public RxMainFrameAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RxMainFrame", "/form[@controlname='RxMainFrame']", parentFolder, 30000, null, true, "547664e6-4cf3-4efa-ab0b-92a0f641feb9", "")
            {
                _tabs = new RanorexFrameworkRepositoryFolders.TabsFolder(this);
                _introduction = new RanorexFrameworkRepositoryFolders.IntroductionFolder(this);
                _test_database = new RanorexFrameworkRepositoryFolders.Test_DatabaseFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("547664e6-4cf3-4efa-ab0b-92a0f641feb9")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("547664e6-4cf3-4efa-ab0b-92a0f641feb9")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Tabs folder.
            /// </summary>
            [RepositoryFolder("9a766960-5fcd-4fe2-928e-12474f79e540")]
            public virtual RanorexFrameworkRepositoryFolders.TabsFolder Tabs
            {
                get { return _tabs; }
            }

            /// <summary>
            /// The Introduction folder.
            /// </summary>
            [RepositoryFolder("a789bdaa-3a71-4ce9-a90f-11eaf28dc252")]
            public virtual RanorexFrameworkRepositoryFolders.IntroductionFolder Introduction
            {
                get { return _introduction; }
            }

            /// <summary>
            /// The Test_Database folder.
            /// </summary>
            [RepositoryFolder("059a9a93-a781-4799-a041-fb05c69be5b9")]
            public virtual RanorexFrameworkRepositoryFolders.Test_DatabaseFolder Test_Database
            {
                get { return _test_database; }
            }
        }

        /// <summary>
        /// The TabsFolder folder.
        /// </summary>
        [RepositoryFolder("9a766960-5fcd-4fe2-928e-12474f79e540")]
        public partial class TabsFolder : RepoGenBaseFolder
        {
            RepoItemInfo _rxtabcontrolInfo;

            /// <summary>
            /// Creates a new Tabs  folder.
            /// </summary>
            public TabsFolder(RepoGenBaseFolder parentFolder) :
                    base("Tabs", "", parentFolder, 0, null, false, "9a766960-5fcd-4fe2-928e-12474f79e540", "")
            {
                _rxtabcontrolInfo = new RepoItemInfo(this, "RxTabcontrol", "tabpagelist[@controlname='RxTabcontrol']", "tabpagelist[@controlname='RxTabcontrol']", 30000, null, "65a579ec-e6d1-4980-ac52-f1914d31f3ef");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9a766960-5fcd-4fe2-928e-12474f79e540")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The RxTabcontrol item.
            /// </summary>
            [RepositoryItem("65a579ec-e6d1-4980-ac52-f1914d31f3ef")]
            public virtual Ranorex.TabPageList RxTabcontrol
            {
                get
                {
                    return _rxtabcontrolInfo.CreateAdapter<Ranorex.TabPageList>(true);
                }
            }

            /// <summary>
            /// The RxTabcontrol item info.
            /// </summary>
            [RepositoryItemInfo("65a579ec-e6d1-4980-ac52-f1914d31f3ef")]
            public virtual RepoItemInfo RxTabcontrolInfo
            {
                get
                {
                    return _rxtabcontrolInfo;
                }
            }
        }

        /// <summary>
        /// The IntroductionFolder folder.
        /// </summary>
        [RepositoryFolder("a789bdaa-3a71-4ce9-a90f-11eaf28dc252")]
        public partial class IntroductionFolder : RepoGenBaseFolder
        {
            RepoItemInfo _lblwelcomemessageInfo;
            RepoItemInfo _btnsubmitusernameInfo;
            RepoItemInfo _txtusernameInfo;
            RepoItemInfo _rxlinkbtnresetInfo;

            /// <summary>
            /// Creates a new Introduction  folder.
            /// </summary>
            public IntroductionFolder(RepoGenBaseFolder parentFolder) :
                    base("Introduction", "", parentFolder, 0, null, false, "a789bdaa-3a71-4ce9-a90f-11eaf28dc252", "")
            {
                _lblwelcomemessageInfo = new RepoItemInfo(this, "LblWelcomeMessage", "?/?/tabpage[@controlname='RxTabIntroduction']/text[@controlname='lblWelcomeMessage']", ".//text[@controlname='lblWelcomeMessage']", 30000, null, "b151cca6-b7dc-4636-9533-e16246e9a615");
                _btnsubmitusernameInfo = new RepoItemInfo(this, "BtnSubmitUserName", "?/?/tabpage[@controlname='RxTabIntroduction']/button[@controlname='btnSubmitUserName']", ".//button[@controlname='btnSubmitUserName']", 30000, null, "eb016da7-b56f-4d51-b8df-a61cc658a46c");
                _txtusernameInfo = new RepoItemInfo(this, "TxtUserName", "?/?/tabpage[@controlname='RxTabIntroduction']/text[@controlname='txtUserName']", ".//text[@controlname='txtUserName']", 30000, null, "a8583479-648a-465a-84cc-c5ac26763b38");
                _rxlinkbtnresetInfo = new RepoItemInfo(this, "RxLinkBtnReset", "?/?/tabpage[@controlname='RxTabIntroduction']/link[@controlname='RxLinkBtnReset']", ".//link[@controlname='RxLinkBtnReset']", 30000, null, "16a9f354-85d8-4fc4-9d45-9663cef747ce");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a789bdaa-3a71-4ce9-a90f-11eaf28dc252")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LblWelcomeMessage item.
            /// </summary>
            [RepositoryItem("b151cca6-b7dc-4636-9533-e16246e9a615")]
            public virtual Ranorex.Text LblWelcomeMessage
            {
                get
                {
                    return _lblwelcomemessageInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LblWelcomeMessage item info.
            /// </summary>
            [RepositoryItemInfo("b151cca6-b7dc-4636-9533-e16246e9a615")]
            public virtual RepoItemInfo LblWelcomeMessageInfo
            {
                get
                {
                    return _lblwelcomemessageInfo;
                }
            }

            /// <summary>
            /// The BtnSubmitUserName item.
            /// </summary>
            [RepositoryItem("eb016da7-b56f-4d51-b8df-a61cc658a46c")]
            public virtual Ranorex.Button BtnSubmitUserName
            {
                get
                {
                    return _btnsubmitusernameInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnSubmitUserName item info.
            /// </summary>
            [RepositoryItemInfo("eb016da7-b56f-4d51-b8df-a61cc658a46c")]
            public virtual RepoItemInfo BtnSubmitUserNameInfo
            {
                get
                {
                    return _btnsubmitusernameInfo;
                }
            }

            /// <summary>
            /// The TxtUserName item.
            /// </summary>
            [RepositoryItem("a8583479-648a-465a-84cc-c5ac26763b38")]
            public virtual Ranorex.Text TxtUserName
            {
                get
                {
                    return _txtusernameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TxtUserName item info.
            /// </summary>
            [RepositoryItemInfo("a8583479-648a-465a-84cc-c5ac26763b38")]
            public virtual RepoItemInfo TxtUserNameInfo
            {
                get
                {
                    return _txtusernameInfo;
                }
            }

            /// <summary>
            /// The RxLinkBtnReset item.
            /// </summary>
            [RepositoryItem("16a9f354-85d8-4fc4-9d45-9663cef747ce")]
            public virtual Ranorex.Link RxLinkBtnReset
            {
                get
                {
                    return _rxlinkbtnresetInfo.CreateAdapter<Ranorex.Link>(true);
                }
            }

            /// <summary>
            /// The RxLinkBtnReset item info.
            /// </summary>
            [RepositoryItemInfo("16a9f354-85d8-4fc4-9d45-9663cef747ce")]
            public virtual RepoItemInfo RxLinkBtnResetInfo
            {
                get
                {
                    return _rxlinkbtnresetInfo;
                }
            }
        }

        /// <summary>
        /// The Test_DatabaseFolder folder.
        /// </summary>
        [RepositoryFolder("059a9a93-a781-4799-a041-fb05c69be5b9")]
        public partial class Test_DatabaseFolder : RepoGenBaseFolder
        {
            RepoItemInfo _departmentInfo;
            RepoItemInfo _ageInfo;
            RepoItemInfo _genderfemaleInfo;
            RepoItemInfo _gendermaleInfo;
            RepoItemInfo _btnaddpersonInfo;
            RepoItemInfo _databaselistInfo;
            RepoItemInfo _btndeletepersonInfo;
            RepoItemInfo _txtfirstnameInfo;
            RepoItemInfo _txtlastnameInfo;

            /// <summary>
            /// Creates a new Test_Database  folder.
            /// </summary>
            public Test_DatabaseFolder(RepoGenBaseFolder parentFolder) :
                    base("Test_Database", "", parentFolder, 0, null, false, "059a9a93-a781-4799-a041-fb05c69be5b9", "")
            {
                _departmentInfo = new RepoItemInfo(this, "Department", "?/?/tabpage[@controlname='RxTabStandard']/combobox[@controlname='cmbDepartment']", ".//combobox[@controlname='cmbDepartment']", 30000, null, "3490e6c1-2af9-4a2d-965f-91b06c6f48b3");
                _ageInfo = new RepoItemInfo(this, "Age", "?/?/tabpage[@controlname='RxTabStandard']/container[@controlname='txtAge']", "", 30000, null, "6428b2a4-cf62-4690-ad00-970450d89ebd");
                _genderfemaleInfo = new RepoItemInfo(this, "GenderFemale", "?/?/tabpage[@controlname='RxTabStandard']/?/?/radiobutton[@controlname='rdbFemale']", ".//radiobutton[@controlname='rdbFemale']", 30000, null, "4996f937-1905-4ec2-bad8-e648ac7b9916");
                _gendermaleInfo = new RepoItemInfo(this, "GenderMale", "?/?/tabpage[@controlname='RxTabStandard']/?/?/radiobutton[@controlname='rdbMale']", ".//radiobutton[@controlname='rdbMale']", 30000, null, "04f684f4-3486-4989-931a-2037ef558a4a");
                _btnaddpersonInfo = new RepoItemInfo(this, "BtnAddPerson", "?/?/tabpage[@controlname='RxTabStandard']/button[@controlname='btnAddPerson']", "?/?/tabpage[@controlname='RxTabStandard']", 30000, null, "c7080998-5f90-4f65-9f4b-936ced3b119c");
                _databaselistInfo = new RepoItemInfo(this, "DatabaseList", "?/?/tabpage[@controlname='RxTabStandard']/list[@controlname='lstPersonList']", ".//list[@controlname='lstPersonList']", 30000, null, "78a360b1-bc75-4d4b-8331-6acccabc4ebc");
                _btndeletepersonInfo = new RepoItemInfo(this, "BtnDeletePerson", "?/?/tabpage[@controlname='RxTabStandard']/button[@controlname='btnDeletePerson']", "?/?/tabpage[@controlname='RxTabStandard']", 30000, null, "e20fb400-490d-4bbd-a3db-b392c991ffb3");
                _txtfirstnameInfo = new RepoItemInfo(this, "TxtFirstName", "?/?/tabpage[@controlname='RxTabStandard']/text[@controlname='txtFirstName']", ".//text[@controlname='txtFirstName']", 30000, null, "d210e0ea-7580-41ba-b114-0b7ae1a2e499");
                _txtlastnameInfo = new RepoItemInfo(this, "TxtLastName", "?/?/tabpage[@controlname='RxTabStandard']/text[@controlname='txtLastName']", ".//text[@controlname='txtLastName']", 30000, null, "2b3cda5d-e300-4618-bf91-31accf564f40");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("059a9a93-a781-4799-a041-fb05c69be5b9")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Department item.
            /// </summary>
            [RepositoryItem("3490e6c1-2af9-4a2d-965f-91b06c6f48b3")]
            public virtual Ranorex.ComboBox Department
            {
                get
                {
                    return _departmentInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The Department item info.
            /// </summary>
            [RepositoryItemInfo("3490e6c1-2af9-4a2d-965f-91b06c6f48b3")]
            public virtual RepoItemInfo DepartmentInfo
            {
                get
                {
                    return _departmentInfo;
                }
            }

            /// <summary>
            /// The Age item.
            /// </summary>
            [RepositoryItem("6428b2a4-cf62-4690-ad00-970450d89ebd")]
            public virtual Ranorex.Container Age
            {
                get
                {
                    return _ageInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Age item info.
            /// </summary>
            [RepositoryItemInfo("6428b2a4-cf62-4690-ad00-970450d89ebd")]
            public virtual RepoItemInfo AgeInfo
            {
                get
                {
                    return _ageInfo;
                }
            }

            /// <summary>
            /// The GenderFemale item.
            /// </summary>
            [RepositoryItem("4996f937-1905-4ec2-bad8-e648ac7b9916")]
            public virtual Ranorex.RadioButton GenderFemale
            {
                get
                {
                    return _genderfemaleInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The GenderFemale item info.
            /// </summary>
            [RepositoryItemInfo("4996f937-1905-4ec2-bad8-e648ac7b9916")]
            public virtual RepoItemInfo GenderFemaleInfo
            {
                get
                {
                    return _genderfemaleInfo;
                }
            }

            /// <summary>
            /// The GenderMale item.
            /// </summary>
            [RepositoryItem("04f684f4-3486-4989-931a-2037ef558a4a")]
            public virtual Ranorex.RadioButton GenderMale
            {
                get
                {
                    return _gendermaleInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The GenderMale item info.
            /// </summary>
            [RepositoryItemInfo("04f684f4-3486-4989-931a-2037ef558a4a")]
            public virtual RepoItemInfo GenderMaleInfo
            {
                get
                {
                    return _gendermaleInfo;
                }
            }

            /// <summary>
            /// The BtnAddPerson item.
            /// </summary>
            [RepositoryItem("c7080998-5f90-4f65-9f4b-936ced3b119c")]
            public virtual Ranorex.Button BtnAddPerson
            {
                get
                {
                    return _btnaddpersonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnAddPerson item info.
            /// </summary>
            [RepositoryItemInfo("c7080998-5f90-4f65-9f4b-936ced3b119c")]
            public virtual RepoItemInfo BtnAddPersonInfo
            {
                get
                {
                    return _btnaddpersonInfo;
                }
            }

            /// <summary>
            /// The DatabaseList item.
            /// </summary>
            [RepositoryItem("78a360b1-bc75-4d4b-8331-6acccabc4ebc")]
            public virtual Ranorex.List DatabaseList
            {
                get
                {
                    return _databaselistInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The DatabaseList item info.
            /// </summary>
            [RepositoryItemInfo("78a360b1-bc75-4d4b-8331-6acccabc4ebc")]
            public virtual RepoItemInfo DatabaseListInfo
            {
                get
                {
                    return _databaselistInfo;
                }
            }

            /// <summary>
            /// The BtnDeletePerson item.
            /// </summary>
            [RepositoryItem("e20fb400-490d-4bbd-a3db-b392c991ffb3")]
            public virtual Ranorex.Button BtnDeletePerson
            {
                get
                {
                    return _btndeletepersonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnDeletePerson item info.
            /// </summary>
            [RepositoryItemInfo("e20fb400-490d-4bbd-a3db-b392c991ffb3")]
            public virtual RepoItemInfo BtnDeletePersonInfo
            {
                get
                {
                    return _btndeletepersonInfo;
                }
            }

            /// <summary>
            /// The TxtFirstName item.
            /// </summary>
            [RepositoryItem("d210e0ea-7580-41ba-b114-0b7ae1a2e499")]
            public virtual Ranorex.Text TxtFirstName
            {
                get
                {
                    return _txtfirstnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TxtFirstName item info.
            /// </summary>
            [RepositoryItemInfo("d210e0ea-7580-41ba-b114-0b7ae1a2e499")]
            public virtual RepoItemInfo TxtFirstNameInfo
            {
                get
                {
                    return _txtfirstnameInfo;
                }
            }

            /// <summary>
            /// The TxtLastName item.
            /// </summary>
            [RepositoryItem("2b3cda5d-e300-4618-bf91-31accf564f40")]
            public virtual Ranorex.Text TxtLastName
            {
                get
                {
                    return _txtlastnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TxtLastName item info.
            /// </summary>
            [RepositoryItemInfo("2b3cda5d-e300-4618-bf91-31accf564f40")]
            public virtual RepoItemInfo TxtLastNameInfo
            {
                get
                {
                    return _txtlastnameInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
