name: Ranorex CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  ranorex-test:
    runs-on: [self-hosted, Windows, X64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Install NuGet
        uses: nuget/setup-nuget@v2

      - name: Restore NuGet packages
        run: nuget restore RanorexFramework.sln

      - name: Build solution
        run: |
          msbuild RanorexFramework/RanorexFramework.sln `
          /p:Configuration=Debug `
          /p:Platform="Any CPU"

      - name: Debug output (check build artifacts)
        run: |
          Get-ChildItem RanorexFramework\bin\Debug -Recurse

      - name: Run Ranorex Tests
        run: |
          $suite = "RanorexFramework\RanorexFramework.rxtst"

          $runner = "RanorexFramework\bin\Debug\RanorexFramework.exe"

          if (!(Test-Path $runner)) {
            Write-Host "Runner not found. Check build output above."
            exit 1
          }

          & $runner $suite /reportfile="TestReport.rxlog.html"